package security.storage;

import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Protects against replay attacks at the transaction level.
 *
 * Every request that must be unique (authentication, payment, order placement)
 * should carry a transaction ID (txId) — typically a UUID generated by the client.
 * Before processing the request, the server calls isReplay(txId).
 * If it returns true, the request is rejected. Otherwise, registerTransaction(txId)
 * is called and the request is processed normally.
 *
 * The cache is bounded: once MAX_CACHE_SIZE entries are reached, the oldest entry
 * is evicted (LRU behaviour via LinkedHashMap). This prevents unbounded memory growth
 * in long-running servers.
 *
 * Thread-safe: all public methods are synchronized.
 */
public class ReplayProtector {

    private static final int    MAX_CACHE_SIZE   = 10_000;
    // Reject any txId whose embedded timestamp is older than this window (seconds)
    private static final long   MAX_AGE_SECONDS  = 300;   // 5 minutes

    /**
     * Cache: txId → registration timestamp (epoch seconds).
     * LinkedHashMap with access-order=false keeps insertion order for LRU eviction.
     */
    private final Map<String, Long> seen = new LinkedHashMap<>(256, 0.75f, false) {
        @Override
        protected boolean removeEldestEntry(Map.Entry<String, Long> eldest) {
            return size() > MAX_CACHE_SIZE;
        }
    };

    // -------------------------------------------------------------------------
    // Public API
    // -------------------------------------------------------------------------

    /**
     * Checks whether a transaction ID has already been seen (replay) or is too old.
     *
     * @param txId the unique transaction identifier from the incoming request
     * @return true  → reject the request (it's a replay or expired)
     *         false → the request is fresh and has not been seen before
     */
    public synchronized boolean isReplay(String txId) {
        if (txId == null || txId.isBlank()) {
            // No txId at all — treat as potential replay/invalid
            return true;
        }
        return seen.containsKey(txId);
    }

    /**
     * Registers a transaction ID as processed.
     * Must be called after isReplay() returns false and before the response is sent.
     *
     * @param txId the unique transaction identifier to record
     */
    public synchronized void registerTransaction(String txId) {
        if (txId == null || txId.isBlank()) return;
        seen.put(txId, Instant.now().getEpochSecond());
    }

    /**
     * Convenience method: atomically checks and registers in one call.
     * Returns true if this is a replay (request should be rejected),
     * false if the txId is fresh (request may proceed — it is now registered).
     *
     * @param txId the transaction identifier to check and register
     * @return true if replay / should be rejected, false if allowed
     */
    public synchronized boolean checkAndRegister(String txId) {
        if (isReplay(txId)) return true;
        registerTransaction(txId);
        return false;
    }

    /**
     * Removes expired entries from the cache based on MAX_AGE_SECONDS.
     * Call this periodically (e.g. on a scheduled background task) to avoid
     * keeping very old entries longer than necessary.
     */
    public synchronized void evictExpired() {
        long cutoff = Instant.now().getEpochSecond() - MAX_AGE_SECONDS;
        seen.entrySet().removeIf(e -> e.getValue() < cutoff);
    }

    /**
     * Returns the current number of tracked transaction IDs (for monitoring / tests).
     */
    public synchronized int cacheSize() {
        return seen.size();
    }

    /**
     * Clears all recorded transactions — useful for test resets only.
     */
    public synchronized void clearForTests() {
        seen.clear();
    }
}